### ISSUE TITLE
AzeriteUI  breaks world map

### ISSUE THREAD

**Issue by BaronSolace** [AzeriteTeam/ClassicWorldMapEnhanced#2]
i took a video to try to show whats going on.    with leatrix maps i can zoom in and out when azeriteUI is enabled i can zoom in,  but not out,  and the cursor becomes off center,   when i disable leatrix maps the map acts as its normal classic none zooming version,   im wondering if maybe any changes to the world map can be removed because its causing conflicts and glitching,   even when using the enhanced maps addon  its still broken.   

https://youtu.be/A2TeuKUwlUg

ignore the backround stream audio,  i forgot to mute them.

**Comment by goldpaw** [comment]
This is bug reports for a standalone map addon, so any bugs related to AzeriteUI + Leatrix really should be reported on the bug tracker of either of this too. This addon is a world map addon for wow classic _only_, and zooming in and out is NOT a map feature there.

**Comment by BaronSolace** [comment]
sorry i didn't realize  i had clicked on the ClassicWorldMapEnhanced  link.
