### ISSUE TITLE
Map Problem with ElvUI

### ISSUE THREAD

**Issue by Lodindogar** [AzeriteTeam/ClassicWorldMapEnhanced#4]
Hy there, like you addon cuz of some level hints for the areas. But there is a scale problem if you use the map with ElvUI. 

The map got even more scaled down and as you can see in the screenshot, the mous pointer is a waaay of ^^

![Snipaste_2019-09-22_08-25-00](https://user-images.githubusercontent.com/15890118/65383241-9b875c00-dd12-11e9-873c-75b56d7a9bec.png)

**Comment by goldpaw** [comment]
Well if ElvUI already adjusts the worldmap, then this addon shouldn't be used with it. I'm marking this as an incompatibility that won't be fixed.
